// Generated by gencpp from file ilk_paket/ros_red.msg
// DO NOT EDIT!


#ifndef ILK_PAKET_MESSAGE_ROS_RED_H
#define ILK_PAKET_MESSAGE_ROS_RED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ilk_paket
{
template <class ContainerAllocator>
struct ros_red_
{
  typedef ros_red_<ContainerAllocator> Type;

  ros_red_()
    : x1(0.0)
    , y1(0.0)  {
    }
  ros_red_(const ContainerAllocator& _alloc)
    : x1(0.0)
    , y1(0.0)  {
  (void)_alloc;
    }



   typedef float _x1_type;
  _x1_type x1;

   typedef float _y1_type;
  _y1_type y1;





  typedef boost::shared_ptr< ::ilk_paket::ros_red_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ilk_paket::ros_red_<ContainerAllocator> const> ConstPtr;

}; // struct ros_red_

typedef ::ilk_paket::ros_red_<std::allocator<void> > ros_red;

typedef boost::shared_ptr< ::ilk_paket::ros_red > ros_redPtr;
typedef boost::shared_ptr< ::ilk_paket::ros_red const> ros_redConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ilk_paket::ros_red_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ilk_paket::ros_red_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ilk_paket::ros_red_<ContainerAllocator1> & lhs, const ::ilk_paket::ros_red_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ilk_paket::ros_red_<ContainerAllocator1> & lhs, const ::ilk_paket::ros_red_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ilk_paket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::ros_red_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ilk_paket::ros_red_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::ros_red_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ilk_paket::ros_red_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::ros_red_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ilk_paket::ros_red_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ilk_paket::ros_red_<ContainerAllocator> >
{
  static const char* value()
  {
    return "448d67037dbf7c4353b30ca654f27801";
  }

  static const char* value(const ::ilk_paket::ros_red_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x448d67037dbf7c43ULL;
  static const uint64_t static_value2 = 0x53b30ca654f27801ULL;
};

template<class ContainerAllocator>
struct DataType< ::ilk_paket::ros_red_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ilk_paket/ros_red";
  }

  static const char* value(const ::ilk_paket::ros_red_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ilk_paket::ros_red_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x1\n"
"float32 y1\n"
;
  }

  static const char* value(const ::ilk_paket::ros_red_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ilk_paket::ros_red_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ros_red_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ilk_paket::ros_red_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ilk_paket::ros_red_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<float>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<float>::stream(s, indent + "  ", v.y1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ILK_PAKET_MESSAGE_ROS_RED_H
